### ISSUE TITLE
Suggestion  - upload and copy link

### ISSUE THREAD

**Issue by FDiskas** [OttoAllmendinger/gnome-shell-screenshot#10]
There is allot of free image storage engines with easy API - for example: imgur.com
Please make ability to upload an image and copy to clipboard automaticly

**Comment by OttoAllmendinger** [comment]
yes, this is absolutely on the top of my to-do list 

I already have some code for this that I just need to integrate

https://github.com/OttoAllmendinger/gnome-shell-imgur

**Comment by FDiskas** [comment]
But thats not works on fedora 25. In screenshot is wisible the selection backgrownd color.

**Comment by FDiskas** [comment]
:black_nib: Looks like: http://i.imgur.com/QrBfD5U.png

**Comment by OttoAllmendinger** [comment]
@FDiskas your screenshot is of gnome-shell-imgur ?

**Comment by OttoAllmendinger** [comment]
Added in https://github.com/OttoAllmendinger/gnome-shell-screenshot/commit/307018e88335a79b751f876c148e9f9522d5c347

**Comment by FDiskas** [comment]
Waiting for the new relese
