### ISSUE TITLE
Error on Fedora 30-GnomeShell 3.32.2

### ISSUE THREAD

**Issue by mprenditore** [OttoAllmendinger/gnome-shell-screenshot#102]
Hello, I was happily using this extension on Fedora 30, but since the latest update to Gnome-shell 3.32.2 it doesn't start any more...
In `journalctl` I've found this when I try to start it:

```
Oct 02 14:59:45 e-fed.enet.lan gnome-shell[7380]: Extension "gnome-shell-screenshot@ttll.de" had error: TypeError: getActorCompat(...).add is not a function
```

But the function *getActorCompat* is correctly defined in the ***indicator.js***

Am I the only one with that issue?

**Comment by OttoAllmendinger** [comment]
This is a known issue, logging out and back in should fix it. 

If it still fails, please try this: https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/97#issuecomment-534525193

**Comment by mprenditore** [comment]
@OttoAllmendinger it worked, thanks :)
