### ISSUE TITLE
Cannot assign keybind to ctrl + shift + 4

### ISSUE THREAD

**Issue by naanlizard** [OttoAllmendinger/gnome-shell-screenshot#106]
Hi, love this except for one problem, I can't set my keybind to select an area to "ctrl + shift + 4" - it renders in the app as "ctrl + $", which seems correct, but it actually is bound to ctrl + 4, no shift.

**Comment by OttoAllmendinger** [comment]
Sadly I haven't found any extension where this works correct so I believe it is an upstream bug.
