### ISSUE TITLE
Suggestion: Set delay for screenshot

### ISSUE THREAD

**Issue by AlexWayfer** [OttoAllmendinger/gnome-shell-screenshot#11]
Hello!

I'm using `gnome-screenshot`, but it doesn't allow take screenshot of selected area with delay.

I'm trying this extension, but it doesn't allow set delay for screenshot at all.

Thanks.

**Comment by OttoAllmendinger** [comment]
Thanks! You're not the first to ask for this: #2 

It's a good idea and I have it planned :)

**Comment by AlexWayfer** [comment]
Oh, sorry for duplicate! 

Thanks!
