### ISSUE TITLE
Not work on ubuntu 20.04

### ISSUE THREAD

**Issue by DmitriyMurzin** [OttoAllmendinger/gnome-shell-screenshot#112]
Not install with error

`JS ERROR: Extension gnome-shell-screenshot@ttll.de: TypeError: GObject_Object.prototype.toString called on incompatible Object
                                             _addSignalMethod@resource:///org/gnome/gjs/modules/signals.js:152:64
                                             addSignalMethods@resource:///org/gnome/gjs/modules/signals.js:158:5
                                             @/home/bart/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/notifications.js:103:1
                                             @/home/bart/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:29:7
                                             _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:379:13
                                             loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:309:22
                                             callback@resource:///org/gnome/shell/ui/extensionDownloader.js:216:17
                                             gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13`

**Comment by OttoAllmendinger** [comment]
please try with https://github.com/OttoAllmendinger/gnome-shell-screenshot/tree/support-336

**Comment by Dazage** [comment]
Works for me on Ubuntu Focal Fossa (development branch) using the support-336 branch.

**Comment by OttoAllmendinger** [comment]
support is now in master branch
