### ISSUE TITLE
Error 256 after created the screenshot

### ISSUE THREAD

**Issue by lwbaqueros** [OttoAllmendinger/gnome-shell-screenshot#113]
When I create an area, window or Desktop screenshot, I got an error in the notification panel: 
`Error: exitCode=256`
The image is not copied to the clipboard.
I am running Ubuntu 20.04

**Comment by lwbaqueros** [comment]
I uninstall firejail and it works again

**Comment by OttoAllmendinger** [comment]
Thanks, I will add a section to the README
