### ISSUE TITLE
Notification no longer shown when screenshot is taken

### ISSUE THREAD

**Issue by ohaessler** [OttoAllmendinger/gnome-shell-screenshot#118]
Thanks a ton for this useful extension. This is really really useful. However, I have an issue with the notification on the latest version of this extension.

OS: RHEL 8
gnome-shell-3.32.2-14.el8.x86_64
the latest extension from extensions.gnome.org

When making a screenshot with the latest version of the extension, the notification is not shown. I get a "dot" next to the time in the Gnome shell to show there is a new notification, but the actual notification is not shown. This worked without issue son the previous version of the extension.

I get the below error in journalctl when making a screenhost:

gnome-shell[18817]: JS ERROR: Exception in callback for signal: notification-added: TypeError: text.replace is not a function
                                                     setTitle@resource:///org/gnome/shell/ui/messageList.js:371:39
                                                     Message@resource:///org/gnome/shell/ui/messageList.js:327:9
                                                     NotificationMessage@resource:///org/gnome/shell/ui/calendar.js:714:9
                                                     _onNotificationAdded@resource:///org/gnome/shell/ui/calendar.js:958:23
                                                     _emit@resource:///org/gnome/gjs/modules/signals.js:142:27
                                                     pushNotification@resource:///org/gnome/shell/ui/messageTray.js:785:9
                                                     notify@resource:///org/gnome/shell/ui/messageTray.js:792:9
                                                     showNotificationCompat@/home/ohaessle/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/notifications.js:58:12
                                                     notifyScreenshot@/home/ohaessle/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/notifications.js:206:3
                                                     _onScreenshot@/home/ohaessle/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:292:7
                                                     _emit@resource:///org/gnome/gjs/modules/signals.js:142:27
                                                     emitScreenshotOnSuccess/<@/home/ohaessle/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/selection.js:191:5
                                                     callHelper/<@/home/ohaessle/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/selection.js:89:5

**Comment by OttoAllmendinger** [comment]
is this still true for the latest version available here? https://extensions.gnome.org/extension/1112/screenshot-tool/

**Comment by ohaessler** [comment]
yes, still true for the latest version

**Comment by OttoAllmendinger** [comment]
please share the output of 

```
cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
```

**Comment by ohaessler** [comment]
cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Conveniently create, copy, store and upload screenshots",
  "gettext-domain": "gnome-shell-screenshot",
  "git-version": "v43-rc1",
  "name": "Screenshot Tool",
  "settings-schema": "org.gnome.shell.extensions.screenshot",
  "shell-version": [
    "3.28",
    "3.30",
    "3.34",
    "3.32",
    "3.36"
  ],
  "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/",
  "uuid": "gnome-shell-screenshot@ttll.de",
  "version": 43

**Comment by ohaessler** [comment]
Do you need anything esle from me for this bug? I checked https://extensions.gnome.org/local/ and i do not see an update for this extension.

Thanks
Oliver

**Comment by OttoAllmendinger** [comment]
no, I just haven't had the time to replicate it yet

maybe you can try an older version and see if that works

```
git checkout v41-rc2;
make install
```

**Comment by ohaessler** [comment]
ok, tried this but `make install` is not working as it gives an error:

```
[ohaessle@ohaessle gnome-shell-screenshot ((v41-rc2))]$ make install
Makefile:7: gselib/make/gnome-shell-extension.mk: No such file or directory
make: *** No rule to make target 'gselib/make/gnome-shell-extension.mk'.  Stop.
```

gselib is indeed empty. Sorry if I missed anything.

**Comment by OttoAllmendinger** [comment]
please do `git submodule update --init` and try agian

**Comment by ohaessler** [comment]
done.

below are the results:

RHEL 8.2
Gnome 3.32.2

install from https://extensions.gnome.org (v43-rc1) - Notifications **not** working
v41-rc2 - extension can not be loaded
v43-rc1 - Notifications **not** working


v45-rc1 - Notification **is** working
v46 - Notification **is** working


Fun fact.. if you install v46, and go to https://extensions.gnome.org, it tells you the extension has an update and if you do the update, it drops the version from v46 to v43-rc1

Hope that helps

**Comment by OttoAllmendinger** [comment]
Thanks!  I disabled 3.32 in more recent version because there were some issues, but it looks like I should enable it.

**Comment by OttoAllmendinger** [comment]
Tested with centos-8 and indeed 3.32 seems to work just fine.  You should be able to use the https://extensions.gnome.org/ version now as well.
