### ISSUE TITLE
Not working "Select Area" on two and more monitors in wayland session

### ISSUE THREAD

**Issue by DmitriyMurzin** [OttoAllmendinger/gnome-shell-screenshot#126]
My conf: 
Ubuntu 20.04 on wayland session.
Dell latitude 7250 laptop.
Two monitors connect via dell dock station.

Select area work on only one monitor.
I select a section on the second monitor, but the screenshot is taken on the first((

**Comment by srid** [comment]
For me, it doesn't work any of the monitors.

**Comment by Migsi** [comment]
Can't reproduce either, running on an Acer Swift 3, external display (WQHD) attached via HDMI, Intel Iris Plus, Wayland.

**Comment by OttoAllmendinger** [comment]
@Migsi -- sorry, do you mean *can* or *cannot* reproduce?

**Comment by Migsi** [comment]
Corrected my comment, sorry for the inconvenience.

**Comment by OttoAllmendinger** [comment]
Please try again on lastest `master`
