### ISSUE TITLE
Filenaming of gnome-screenshot

### ISSUE THREAD

**Issue by gsantner** [OttoAllmendinger/gnome-shell-screenshot#13]
Hi there,
could you please make the default naming scheme follow/like the `gnome-screenshot` application? 
It's quite bad (and unsortable) the current way.

Naming of `gnome-screenshot`:
`{  T R A N SLATION     }»Year-Month-Day Hour-Min-Sec«.png`  
`Bildschirmfoto von »2016-12-27 03-23-56«.png`

If #9 gets implemented, please allow this as a template, or make it default.

**Comment by OttoAllmendinger** [comment]
Please test the master branch

**Comment by gsantner** [comment]
@OttoAllmendinger 
Thanks! Works on my 3.22 shell
