### ISSUE TITLE
[feature request] provide option to save screenshot as jpg

### ISSUE THREAD

**Issue by meiser79** [OttoAllmendinger/gnome-shell-screenshot#136]
Hi,

thanks for developing this great extension, it helps me a lot during my daily business work.

I'd like to ask to provide a configuration option to save the screenshots as jpg.

Many thanks in advance,
meiser

**Comment by OttoAllmendinger** [comment]
does https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/15 sound like a good solution for you? This tool should do the job https://imagemagick.org/script/convert.php

**Comment by meiser79** [comment]
Should work, yes.
