### ISSUE TITLE
gselib results in 404 not found

### ISSUE THREAD

**Issue by dottorblaster** [OttoAllmendinger/gnome-shell-screenshot#137]
Hi!

I was trying to install the extension from git, but `f8aca72cbef1d012a5a27847e20e89e3158e0a18` could not be found while cloning the repository. Same, if you try to click on the sunmodule directory on the front page of the repo it results in a 404. Maybe the submodule is pointing at some unexisting ref?

**Comment by OttoAllmendinger** [comment]
should be fixed on latest master

**Comment by dottorblaster** [comment]
It is! Thanks :partying_face:
