### ISSUE TITLE
Tool unusable, ERROR.

### ISSUE THREAD

**Issue by natsudragneel-x** [OttoAllmendinger/gnome-shell-screenshot#138]
The tool was working fine before the update. As soon as I updated it, it stopped working and just says error now. Tried reinstalling but it's still the same. I'm using GNOME 3.38 and Arch Linux.

**Comment by OttoAllmendinger** [comment]
please log out and log back in again

https://github.com/OttoAllmendinger/gnome-shell-screenshot#error-after-updating-extension-gnome-shell-337-and-above

**Comment by natsudragneel-x** [comment]
> please log out and log back in again
> 
> https://github.com/OttoAllmendinger/gnome-shell-screenshot#error-after-updating-extension-gnome-shell-337-and-above

I had already tried that, didnt work after relogin but it did work after restarting. Thanks.
