### ISSUE TITLE
Extension UI not shown in system language

### ISSUE THREAD

**Issue by Etamuk** [OttoAllmendinger/gnome-shell-screenshot#139]
Hello,

I have installed your extension and noticed the UI is English. 
A german translation file is installed but the extension is not shown with a german UI. 
Ext-version: 54
System: Fedora 33 GNOME 3.38.2 (locale: de)
Is there a way to fix this?

Kind regards from Germany :-)

**Comment by OttoAllmendinger** [comment]
Dankeschön! Should be fixed now

**Comment by Etamuk** [comment]
Danke! 
Teilweise stimmt es. 
Aber nicht alles ist in deutsch.


https://user-images.githubusercontent.com/20098065/103351817-b2d00000-4aa4-11eb-9df4-4d93e43b2cf9.mp4

**Comment by OttoAllmendinger** [comment]
stimmt, ich muss noch ein paar Stellen ergänzen #140
