### ISSUE TITLE
Copying Images to clipboard doesn't work

### ISSUE THREAD

**Issue by ayoisaiah** [OttoAllmendinger/gnome-shell-screenshot#14]
Fedora 24, Gnome 3.20

When I try to copy a screenshot to the clipboard and then paste into a program (such as GIMP), it doesn't work. Meanwhile using the default Ctrl+PrintSrc shortcut works. Can you reproduce that?

**Comment by OttoAllmendinger** [comment]
Maybe it's a duplicate of #4.

Does it work again after restarting the shell? `Ctrl-F2 r <Enter>`

I did not find a good fix for it and it was solved by Gnome 3.22. 

Maybe I'll backport the feature described in #15 to a version that supports Gnome 3.20

**Comment by AdrianKuriata** [comment]
#36
