### ISSUE TITLE
Can't change default command

### ISSUE THREAD

**Issue by lamehost** [OttoAllmendinger/gnome-shell-screenshot#141]
I've installed the extension via https://extensions.gnome.org/ and -although the command switch option works- i can't make gnome-shell-screenshot to run anything but `gimp {f}`.

It looks like the command string you type in is completely ignored. It is not saved after you close the settings dialog window and doesn't take effect if you change it and keep the window open.

Step to reproduce:

1. Download tool from https://extensions.gnome.org/ 
2. Open settings
3. Change command
4. Screen capture

**Comment by lamehost** [comment]
Works after last update. 
metadata.json says: "git-version": "v56"

**Comment by OttoAllmendinger** [comment]
thanks for the report!
