### ISSUE TITLE
Zone selection captures the overlay

### ISSUE THREAD

**Issue by phocean** [OttoAllmendinger/gnome-shell-screenshot#16]
The reddish overlay is captured along with the selected area.

This illustration is worth many words:

![screenshot-20170102143849-543x277](https://cloud.githubusercontent.com/assets/4280885/21808229/9f5af1b2-d742-11e6-9341-f210094a157b.png)

**Comment by OttoAllmendinger** [comment]
Can you tell me the OS and the gnome version you're using?

**Comment by phocean** [comment]
I am on Fedora 25, Wayland, Gnome 3.22.2.

**Comment by OttoAllmendinger** [comment]
Please test with current master branch

**Comment by phocean** [comment]
Yes, it is working well so far. Thank you :-)
