### ISSUE TITLE
Incompatible with Gnome 41

### ISSUE THREAD

**Issue by zrno** [OttoAllmendinger/gnome-shell-screenshot#165]
Stopped working since I updated to Gnome 41.

**Comment by Modedrain** [comment]
Can confirm, same issue. Selection cursor/window mark shows up when pressing hotkey but no image gets taken since upgrading to gnome 41

**Comment by diwakargoel** [comment]
duplicate of https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/158

**Comment by hadeschen** [comment]
臣，复议！

**Comment by OttoAllmendinger** [comment]
Please try #168

**Comment by OttoAllmendinger** [comment]
duplicate of #158
