### ISSUE TITLE
TypeError this.gtkImage.pixbuf is null

### ISSUE THREAD

**Issue by domhaas** [OttoAllmendinger/gnome-shell-screenshot#166]
Since I've switched from Ubuntu to Manjaro (Gnome 41.1) I'm getting these two errors when creating a screenshot:

`error: exitCode=256`
`TypeError this.gtkImage.pixbuf is null`

Am I missing something? Couldn't find anything with these errors. Thank you in advance.

**Comment by domhaas** [comment]
Possible duplicate of #165

**Comment by MisterPresident** [comment]
I have the same issue, any solutions yet?

**Comment by OttoAllmendinger** [comment]
This particular issue should be fixed on the `master` branch

However there are other issues with Gnome41 that need fixing.

**Comment by OttoAllmendinger** [comment]
duplicate of #158
