### ISSUE TITLE
Don't save screens

### ISSUE THREAD

**Issue by Dicoders** [OttoAllmendinger/gnome-shell-screenshot#170]
![Без имени](https://user-images.githubusercontent.com/8055462/143979662-5110b58b-2b0d-4764-9006-25dfbb8e8ffe.png)

After update for gnome 41.1 im getting this error. Capture is correct, but error get after click share.
Fedora 35 X11 GNOME 41.1

**Comment by OttoAllmendinger** [comment]
Should be fixed in latest `master`
