### ISSUE TITLE
Doesn't work with Gnome 41 - even after update to Screenshot Tool v61

### ISSUE THREAD

**Issue by speendo** [OttoAllmendinger/gnome-shell-screenshot#171]
So I updated the tool to v61 on my system with Debian Testing installed.

When I select `Open Portal` I get this
![grafik](https://user-images.githubusercontent.com/1668429/144071569-6b2157a1-ee3f-4831-a0e0-f8ea0cfa0d19.png)

Otherwise, when I try to select one of the other options, I get "Error: Not available for Gnome 41"

The latter one is probably expected behavior, isn't it?

The first one, however really ... reduces ... the usability of the tool.

Please let me know if I can provide any additional information.

**Comment by oxayotl** [comment]
You need to install the right package. On ArchLinux it was called xdg-desktop-portal . It's still incredibly worse than it was before, but I guess the Gnome gods are fickle mistresses and all that ^^

**Comment by speendo** [comment]
hmmI fear that doesn't solve the problem

![grafik](https://user-images.githubusercontent.com/1668429/144132532-77fb8787-208d-41b4-8a7e-0c57be56aeed.png)

**Comment by bickkysahani** [comment]
same here it doesnt work in fedora gnome 41 wayland

**Comment by netroy** [comment]
I'm having the same issue on Gnome 41 on Manjaro.
Interestingly if I right click, and "Open Portal", all three modes work just fine from that UI. 

but, using either the keyboard shortcut, or clicking on the systray icon gives me this
> Error: Not available for Gnome 41

**Comment by OttoAllmendinger** [comment]
Yes, for now "Open Portal" is the only available option for Gnome 41.

The other capture methods are not available to me any longer.

**Comment by speendo** [comment]
Thanks for clarifying @OttoAllmendinger.
However, on my system "Open Portal" doesn't work either.

**Comment by prasket** [comment]
Confirmed same error using Debian Bookworm & Gnome 41.1
I get an error when clicking on `Open Portal` about `No such interface...` but do have xdg-desktop-portal  & gnome-screenshot installed as well. 

Right now only way I can take screenshots is to open gnome-screenshot and use it.

**Comment by MBilderbeek** [comment]
FYI: here on Debian testing (gnome-shell 41.1-1), the open portal options work fine, the others give the error "Not available on gnome 41."

**Comment by pacho2** [comment]
If it is impossible to fix it for Gnome 41, I would simply replace the options to simply add a clickable icon in the shell bar to directly open the screenshot dialog. That way it is faster to take the screenshot... even if not so as it was before that we were able to directly choose what kind of screenshot to take and to get it saved automatically to the clipboard :(

I am also unsure if it would be possible to add a preference to choose to run in "unsafe" mode if wanted allowing to use as before

**Comment by OttoAllmendinger** [comment]
it is possible to open the portal with a single click by setting the "Primary Button" option: 
![image](https://user-images.githubusercontent.com/283533/146342026-a31d6d46-9a4b-4a36-8e69-de87f9a19374.png)

I am considering these options to restoring the original features:

* Give instructions how to enable unsafe-mode easily (I suspect having code in my extension to set unsafe mode would not be allowed in the store)
* Gnome-shell source code has a hardcoded whitelist for programs that are allowed to use the private screenshot API. I could provide instructions on how to add the extension to that list. Then unsafe-mode would not be required.
* Option to shell out to an external tool like https://github.com/emersion/grim (for Wayland) or https://github.com/resurrecting-open-source-projects/scrot (X11)

Sadly I don't have much time to work on this right now.

**Comment by pacho2** [comment]
Thanks for the help :) 

the only issue is that it seems that portal window gets opened behind the previous windows :/ But maybe it's an issue of the portal

Regarding the use of external tools, why not calling native gnome-screenshot app instead of grim/scrot?

**Comment by OttoAllmendinger** [comment]
Yes, `gnome-screenshot` would also be a good option

**Comment by pacho2** [comment]
> * Gnome-shell source code has a hardcoded whitelist for programs that are allowed to use the private screenshot API. I could provide instructions on how to add the extension to that list. Then unsafe-mode would not be required.

I think this would be the best option for the short-term :)

Thanks a lot!

**Comment by OttoAllmendinger** [comment]
New version is pushed to master and pending review in the extension store. 

t uses the `gnome-screenshot` cli tool as the default backend.

Not quite like pre-Gnome40 behavior since the selection highlighting is missing, but much better than the portal option.

**Comment by pacho2** [comment]
It works nice

Thanks a lot :D

As a side note, my first tries were silently failing to get the screenshots saved because I had a gnome-screenshot instance opened in a different virtual desktop. I understand it is a really corner case... but I say it for the case someone else hits the same issue some day
