### ISSUE TITLE
Not working Properly in Fedora 35 gnome 41 wayland

### ISSUE THREAD

**Issue by bickkysahani** [OttoAllmendinger/gnome-shell-screenshot#172]
The open portal option is working fine but the options such select area, select window, select desktop is not working. when I try to click on any of that option, it throws an error.

It says: Error Not Available for Gnome 41
![Screenshot from 2021-12-01 10-46-19](https://user-images.githubusercontent.com/49335486/144174992-58c0ce7b-fd1a-4917-98a2-4d6e2d8a1a3b.png)

**Comment by oxayotl** [comment]
Yes, this is known and because of a change by Gnome devs:
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1970#note_1288230

**Comment by dipunm** [comment]
Is this something that is being planned to get fixed or are there recommendations for alternatives?

**Comment by OttoAllmendinger** [comment]
See #171
