### ISSUE TITLE
Keep 2 Versions of gnome-shell-screenshot? 

### ISSUE THREAD

**Issue by steviehs** [OttoAllmendinger/gnome-shell-screenshot#173]
as "something" updated my screenshot tool, which I installed from the unsafe-mode branch, I changed - in dumb mode - any appearance of gnome-shell-screenshot@ttll.de to gnome-shell-screenshot-nsm@ttll.de being aware, that this way of hitchhiking it is not the supposed one :-)

But it would maybe the way to go - at least so long there is not improvement from gnome side - to provide two versions: one restricted to what is possible in safe mode, one which works as we all love and be aware that we run unsafe mode for it?

The two most important features of gnome-shell-screenshot are for me: easy area selection (and delay setting for that) _and_ (even more important) the easy way to access this picture and even copy paste it just from the notification area.

**Comment by OttoAllmendinger** [comment]
I hope the latest version on `master` is good enough even without unsafe-mode

**Comment by steviehs** [comment]
Definitely! With the possibility to copy the last picture directly to the clipboard it is great! Thanx a lot!
