### ISSUE TITLE
When I click on any option, nothing happens [ Fedora 34 ]

### ISSUE THREAD

**Issue by FGYada1984** [OttoAllmendinger/gnome-shell-screenshot#175]
Last Sunday I updated my system. Everything is ok, but the extension stopped working, what happens is that when I click on any option, nothing happens. Using `journalctl -f` the error I get is:

```
fedora gnome-shell[3188]: JS ERROR: Error: Could not guess unspecified GValue type
                                          activate@resource:///org/gnome/shell/ui/popupMenu.js:191:14
                                          vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14
```

Specs:
```
OS: Fedora 34 (Workstation Edition) x86_64 
Kernel: 5.15.11-100.fc34.x86_64 
Shell: fish 3.3.1 
Resolution: 3440x1440, 1920x1080, 1920x1080 
DE: GNOME 40.7 
WM: Mutter 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: NVIDIA GeForce RTX 2060 Mobile 
Memory:  31951MiB 
```

I have already uninstalled and installed from both extensions.gnome and here, I need help, this extension is simple and perfect for my daily use.

**Comment by OttoAllmendinger** [comment]
can you give the output of the following command

```
cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
```

**Comment by FGYada1984** [comment]
> `cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json`

```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Conveniently create, copy, store and upload screenshots",
  "gettext-domain": "gnome-shell-screenshot",
  "git-version": "v63",
  "name": "Screenshot Tool",
  "settings-schema": "org.gnome.shell.extensions.screenshot",
  "shell-version": [
    "40",
    "41"
  ],
  "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/",
  "uuid": "gnome-shell-screenshot@ttll.de",
  "version": 63
}⏎       
```

**Comment by OttoAllmendinger** [comment]
I suspect the `Could not guess unspecified GValue type` is unrelated since I see it too but the extension still works in my Fedora 34 environment.

Could you give me the output of

```
gnome-screenshot --version
```

And of

```
gnome-screenshot -f /tmp/gss.png && file /tmp/gss.png
```

**Comment by FGYada1984** [comment]
This is strange and even a little embarrassing, because I have the gnome-screenshot application installed -and it is not a default installation?- but when I went to give the command you asked for, I was asked if I wanted to install it. Installation done, it's back up and running. 

Problem solved. I take this opportunity to thank you for this very useful extension.

**Comment by OttoAllmendinger** [comment]
Good to know! I will add a check for this condition
