### ISSUE TITLE
Gnome 41 Support Needed!

### ISSUE THREAD

**Issue by hchen98** [OttoAllmendinger/gnome-shell-screenshot#177]
Hi there,

When will there be support for Gnome 41? I know there's v.63 but the shortcut screenshot doesn't work. The same thing applies to versions 61 - 62.

**Comment by OttoAllmendinger** [comment]
what do you mean by "the shortcut screenshot doesn't work"?

**Comment by hchen98** [comment]
> 

I know the repo doc mentioned a solution to resolve this (https://github.com/OttoAllmendinger/gnome-shell-screenshot#error-exitcode256) but I did not use 'firejail' at all. Here you go for the screenshot of the error message:
![Screenshot from 2022-01-10 13-52-54__2](https://user-images.githubusercontent.com/12217705/148822931-f9552e33-3b4d-42c4-be0f-8dedf298456f.png)

**Comment by OttoAllmendinger** [comment]
do you have the `gnome-screenshot` tool installed?

**Comment by hchen98** [comment]
The screenshot tool I have used is this:
![Screenshot-20220111094725-476x392](https://user-images.githubusercontent.com/12217705/148964957-2f2f7471-9333-4381-b816-3b7c9655e8a4.png)

**Comment by bttger** [comment]
@hchen98 Try updating your gnome-screenshot version. The current version is 41.0.

**Comment by hchen98** [comment]
> @hchen98 Try updating your gnome-screenshot version. The current version is 41.0 for me and it works.

@bttger ah, I see. I guess that's caused the issue. Unfortunately, I am using Ubuntu 20.04 but installed unofficial Gnome 41 on my desktop, so unable to update the gnome-screenshot tool. I will close this issue. Thanks for replying! :) Stay safe!
