### ISSUE TITLE
Error while trying to take a screenshot (area, window and desktop)

### ISSUE THREAD

**Issue by pflanzenandi** [OttoAllmendinger/gnome-shell-screenshot#178]
GLib.spawnError: Failed to execute child process ''gnome screenshots'' (no such file or directory)

NAME="Pop!_OS"
VERSION="21.10"
GNOME=''40.4.0''

**Comment by OttoAllmendinger** [comment]
Please make sure you have the `gnome-screenshot` installed

I think it should work similar to this: https://zoomadmin.com/HowToInstall/UbuntuPackage/gnome-screenshot

**Comment by pflanzenandi** [comment]
That worked. Is the [gnome.extension package](https://extensions.gnome.org/extension/1112/screenshot-tool/) broken?

**Comment by OttoAllmendinger** [comment]
No, it is just missing a check for this dependency. The tool is typically installed but not always.
