### ISSUE TITLE
Auto-copy to Clipboard copies imgur link instead of Image Data when set to Image data

### ISSUE THREAD

**Issue by corebots** [OttoAllmendinger/gnome-shell-screenshot#182]
This seems to be happening since latest update or so. I was always able to past the image after taking a screenshot, but now it only pasts the imgur link.
![image](https://user-images.githubusercontent.com/12252430/151513011-cbb49234-680e-446b-90ed-6969695c9e36.png)

**Comment by OttoAllmendinger** [comment]
Please check the "Imgur" tab if the setting "Auto-Copy Link After Upload" is enabled

**Comment by corebots** [comment]
Ah damn, looks like that was it. Thank you!

**Comment by OttoAllmendinger** [comment]
I must admit that UI is not great :)

**Comment by corebots** [comment]
Still a very helpful extension! Thanks for the work!
