### ISSUE TITLE
Gnome 42 Support needed

### ISSUE THREAD

**Issue by vageliskatsiotis** [OttoAllmendinger/gnome-shell-screenshot#186]
Hi there. After last upgrade to plugin does not seem to work. I've tried to add the version 42 in metadata.json with no success

**Comment by oxayotl** [comment]
There is already a pull request fixing this if you want @vageliskatsiotis :
https://github.com/OttoAllmendinger/gnome-shell-screenshot/pull/185

**Comment by vageliskatsiotis** [comment]
@oxayotl great, thanx! It did not catch my eye while searching

**Comment by vageliskatsiotis** [comment]
Ok, for some reason this did not work before but now does. So thanx for the tip @oxayotl
