### ISSUE TITLE
Error after upgrading from PopOS 21.10 to 22.04 LTS (Failed to execute child process)

### ISSUE THREAD

**Issue by J-onasJones** [OttoAllmendinger/gnome-shell-screenshot#187]
As of today, PopOS 22.04 LTS is available and I took that opportunity to upgrade. After the upgrade, all my Gnome Extensions were gone and upon reinstalling the Screenshot extension and testing it, it errors out. All my config from the old installation was reapplied, even the Shortcut I had set (SUPER + SHIFT + S). The error message is the following:

`ERROR: backend gnome-screenshot GLib.SpawnError: Failed to execute child process "gnome-screenshot" (No such file or directory)`

In what way can this be fixed?

**Comment by OttoAllmendinger** [comment]
please try installing the "gnome-screenshot" tool: https://github.com/OttoAllmendinger/gnome-shell-screenshot#errors-with-gnome-screenshot-backend

**Comment by OttoAllmendinger** [comment]
Ok it appears that link in the README is dead. This is the tool: https://gitlab.gnome.org/GNOME/gnome-screenshot

**Comment by J-onasJones** [comment]
I have installed it from the official gnome extensions website (https://extensions.gnome.org/) but I couldn't figure out how to install it from the gitlab link. Are those two versions any different? And if yes, how do I install it from gitlab?

**Comment by yash3492** [comment]
You should be installing it via `apt-get install gnome-screenshot`.

It worked for me after installing GNOME Screenshot.

Thanks!
