### ISSUE TITLE
Ubuntu 22.04 LTS - gnome shell screenshot tool extension not working

### ISSUE THREAD

**Issue by gyfary** [OttoAllmendinger/gnome-shell-screenshot#188]
gnome-shell --version
GNOME Shell 42.0

journalctl --user /usr/bin/gnome-shell --follow

Apr 30 20:06:10 Thinkpad gnome-shell[2789]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                              wrapNotifyError/<@/home/abdurrahman/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:735:31
                                              activate@resource:///org/gnome/shell/ui/popupMenu.js:197:14
                                              vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:141:14

**Comment by witszymanski** [comment]
Same here. 
Using and older version of the  gives and error that gnome-screenshot cannot be activated. 
Upgrading to the newest version gives a straightforward error:
![image](https://user-images.githubusercontent.com/15866068/167085631-300e73bf-b19a-42e5-a473-ca0efc274784.png)

Greets!

**Comment by witszymanski** [comment]
![image](https://user-images.githubusercontent.com/15866068/167087353-3f604382-936d-4ba1-ba18-6dcb600a5c4b.png)

**Comment by serhiyburkow** [comment]
> After upgrading to 22.04 LTS it stopped working here. I reinstalled it, logged out and in (which remeved the error) but I still cannot make it work.
> 
> ![image](https://user-images.githubusercontent.com/15866068/167087353-3f604382-936d-4ba1-ba18-6dcb600a5c4b.png)
> 
> Greets

You just need to install gnome-screenshot through apt-get

**Comment by witszymanski** [comment]
![image](https://user-images.githubusercontent.com/15866068/167089813-e72b4fef-0c3a-440b-b538-1361b574120f.png)

Where is the FACE PALM emoticon here??? 

Thanks man!!

**Comment by gyfary** [comment]
> > After upgrading to 22.04 LTS it stopped working here. I reinstalled it, logged out and in (which remeved the error) but I still cannot make it work.
> > ![image](https://user-images.githubusercontent.com/15866068/167087353-3f604382-936d-4ba1-ba18-6dcb600a5c4b.png)
> > Greets
> 
> You just need to install additionaly gnome-screenshot through apt-get

thanks man!
its working now.
just 
apt install gnome-screenshot
