### ISSUE TITLE
Gnome 43 support

### ISSUE THREAD

**Issue by voodooattack** [OttoAllmendinger/gnome-shell-screenshot#191]
Seems like the extension works fine on Gnome 43 (just tested it and everything is working well), it just needs to be added to `shell-version` in `metadata.json`.

**Comment by RaphaelJenni** [comment]
For anyone looking for it: `~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json`

**Comment by GlenMerlin** [comment]
yeah #190 has the required change if anyone wants to do it manually. Testing it out myself now but it appears to work just fine

**Comment by jcklpe** [comment]
Still not working for me in Ubuntu 22.0.4?

**Comment by jcklpe** [comment]
Getting a "Glib: Spawn Error" whatever that means.

**Comment by OttoAllmendinger** [comment]
@jcklpe if the issue persists, please open a new ticket
