### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by pacho2** [OttoAllmendinger/gnome-shell-screenshot#198]
Gnome 44 was released some days ago and it seems the extension needs to add support for it

Thanks a lot!

**Comment by pacho2** [comment]
Simply updating the metadata works (just tested locally)

**Comment by a4orce84** [comment]
Can you go through the steps on what's involved to update the metadata? I just updated to Gnome 44.1 on Manjaro Gnome and this extension broke.

Any help would be greatly appreciated.

**Comment by demizer** [comment]
> Can you go through the steps on what's involved to update the metadata? I just updated to Gnome 44.1 on Manjaro Gnome and this extension is now broken.
> 
> Any help would be greatly appreciated.

1. Clone git repo
2. Edit metadata json to change 43 to 44
3. Run `make install` from project root

**Comment by a4orce84** [comment]
Thanks! 

Is there a way to modify the metadata if I already have the extension installed, it's just not 'starting' in the Gnome Extensions Manager? I have it installed pre-Gnome 44.1 upgrade, so just looking to 'hack' the existing metadata if possible.

**Comment by pacho2** [comment]
Modifying ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json should be enough

**Comment by a4orce84** [comment]
Awesome, thank you @pacho2, that fixed it!
