### ISSUE TITLE
Suggestion / Add optional capture delay

### ISSUE THREAD

**Issue by RaphaelRochet** [OttoAllmendinger/gnome-shell-screenshot#2]
Sometimes a small time is needed to have what we want to capture, like a popup menu or a drop-down list.

**Comment by orschiro** [comment]
Would be so amazing! Any updates on this? :-)

**Comment by OttoAllmendinger** [comment]
fixed in master, https://extensions.gnome.org/extension/1112/screenshot-tool/ pending approval

**Comment by orschiro** [comment]
Yeah, thanks Otto! :-) What a great new release.
