### ISSUE TITLE
Imgur upload fails with 'TypeError: upload is undefined'

### ISSUE THREAD

**Issue by reidhekman** [OttoAllmendinger/gnome-shell-screenshot#203]
After selecting an area to screenshot, "Imgur Upload" notification appears in the notification area, then after a few seconds, another "Error TypeError: upload is undefined" notification appears.

Journal contains the following:
`Dec 29 19:55:39 richville gnome-shell[3177]: JS WARNING: [resource:///org/gnome/shell/ui/calendar.js 1037]: Too many arguments to method Clutter.Actor.hide: expected 0, got 1

Dec 29 19:55:39 richville gnome-shell[3177]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around>
                                               wrapNotifyError/<@file:///home/reidh/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:1172:27
                                               activate@resource:///org/gnome/shell/ui/popupMenu.js:194:14
                                               _init/<@resource:///org/gnome/shell/ui/popupMenu.js:111:24
                                               @resource:///org/gnome/shell/ui/init.js:21:20
`

Extension Settings enabled include "Enable Imgur Upload", "Show Upload Notification", "Auto-Upload After Capture", and "Auto-Copy Link After Upload".

Environment is Gnome 45.2, Wayland, EndeavorOS(Arch)

**Comment by reidhekman** [comment]
Reproduced with Gnome on Xorg session.
Also reproduced with no other extensions enabled.

**Comment by OttoAllmendinger** [comment]
thank you! should be fixed in latest master
