### ISSUE TITLE
Adding a tab with 'About/Version' information

### ISSUE THREAD

**Issue by yafp** [OttoAllmendinger/gnome-shell-screenshot#21]
Right now a user can only guess which version of gnome-shell-screenshot he is using as far as i tell.
The metadata.json does not contain a version info either.

The following is supported in metadata.json:

> "version": 1

A version number could simply be the commit  date or similar if you dislike complex versioning

**Why a version number:**
I already managed to overwrite my current installed version of gnome-shell-screenshot (with an older version) while visiting https://extensions.gnome.org/ and trusting the offered update-notification.

**Ideas about how to**
I would love to see an additional tab in the UI featuring:
* version number
* the project url 

and maybe optional 
* developer name, 
* license and whatever else

If you dislike the idea of an additional tab - how about a small gray footer text on the current UI-tabs.

**Comment by OttoAllmendinger** [comment]
> Why a version number:

> I already managed to overwrite my current installed version of gnome-shell-screenshot (with an older version) while visiting https://extensions.gnome.org/ and trusting the offered update-notification.

Unfortunately the version number gets assigned by extensions.gnome.org, so I can't influence that. I will add an extra git version field for informational purposes, but it's difficult to make repo-installed versions work together with e-g-o versions. Maybe installs from the git repo should just have a different UUID?

**Comment by RaphaelRochet** [comment]
On my extensions, I manually set the version in metadata.json (simply doing +1 when releasing to ego). Doesn't cost much and it seems to fix wrong update notifications error. 
I don't think that ego change the version in metadata.json, it's only on the website.
