### ISSUE TITLE
icon gone?

### ISSUE THREAD

**Issue by eexpress** [OttoAllmendinger/gnome-shell-screenshot#24]
icon become blank one. Does it use the emplty64.png?

![-2017-03-02-17 41 46-784x343](https://cloud.githubusercontent.com/assets/700793/24141238/d9e40d76-0e5d-11e7-8b91-28c8edd7ef53.png)

**Comment by OttoAllmendinger** [comment]
Can you share the OS and the version of gnome-shell?

**Comment by OttoAllmendinger** [comment]
> Does it use the empty64.png?

Not as the tray icon. The tray icon uses the icon `camera-photo-symbolic` that should be provided by gnome.

**Comment by eexpress** [comment]
Sorry about delayed feedback. It not a bug. I had found this icon depends on the theme.
