### ISSUE TITLE
Uploading on imgur not working?

### ISSUE THREAD

**Issue by AdrianKuriata** [OttoAllmendinger/gnome-shell-screenshot#36]
Hi, i installed new version for screen shoting but i don't have options with uploading on imgur. I just have select area, select window, whole window and settings, into settings i don't have tabs with imgur like on screenshop in readme, did you tell me what can i do for uploading screens on imgur? Thanks for the patient!

**Comment by AdrianKuriata** [comment]
After do ScreenShot it should be copied to clipboard? I set in settings image data should be copied to the clipboard but this is not working for me, i restarted shell but is same problem. 

GNOME Shell: 3.20.4
Fedora 24

**Comment by OttoAllmendinger** [comment]
Sorry, the updated version that includes imgur support is still pending review on extensions.gnome.org

**Comment by AdrianKuriata** [comment]
@OttoAllmendinger Ohhh, thanks for your answer, i will waiting for it.
