### ISSUE TITLE
Option to copy Imgur Link automatically after upload

### ISSUE THREAD

**Issue by sojusnik** [OttoAllmendinger/gnome-shell-screenshot#39]
Would be nice to have the option "copy URL to clipboard" from your outdated imgur extension back in this one.

**Comment by OttoAllmendinger** [comment]
Do you mean the option to copy the link automatically after capture? 

There is a "Copy Link" button on the notification and a "Copy Link" item in the popup menu.

**Comment by sojusnik** [comment]
> Do you mean the option to copy the link automatically after capture?

Yes.

> There is a "Copy Link" button on the notification and a "Copy Link" item in the popup menu.

I know, but having it copied automatically to the clipboard is even more convenient.

**Comment by OttoAllmendinger** [comment]
Ok, just checking :)

I'm working on it but it requires a little refactor in prefs.js. Stay tuned!

**Comment by FDiskas** [comment]
:necktie: And the option to upload screenshot to imgur automatically would be awesome to.

**Comment by sojusnik** [comment]
@FDiskas This is already implemented. Have a look at the extensions' settings.

**Comment by OttoAllmendinger** [comment]
@sojusnik automatic upload isn't implemented yet, you still have to launch the action yourself.

**Comment by OttoAllmendinger** [comment]
![image](https://cloud.githubusercontent.com/assets/283533/26407580/dbdc4308-409b-11e7-9c19-a80944fefbbd.png)

pending review on e.g.o

**Comment by FDiskas** [comment]
How to get latest version? :finnadie:
![vytenis kuciauskas-20170523165449-297x333](http://i.imgur.com/GQq5Ffu.png)

**Comment by OttoAllmendinger** [comment]
@FDiskas either follow the instructions here https://github.com/OttoAllmendinger/gnome-shell-screenshot#via-githubcom

or wait until it is approved on extensions.gnome.org (could take a week)
