### ISSUE TITLE
Add a "clear" feature/menu item

### ISSUE THREAD

**Issue by ddnexus** [OttoAllmendinger/gnome-shell-screenshot#40]
Remove an old screenshot (still shown in the dropdown) that the user may not want anymore. It could be done automatically after a few seconds/minutes (option in settings) or even just manually with a "Clear" menu item. Thanks!

**Comment by OttoAllmendinger** [comment]
Duplicate of #37 

The extension is still pending review on extensions.gnome.org though, sorry. If you want you can also install from the git repo.

**Comment by ddnexus** [comment]
Oh... great!!! Thanks!
