### ISSUE TITLE
Ability to delay the screenshot

### ISSUE THREAD

**Issue by olymk2** [OttoAllmendinger/gnome-shell-screenshot#43]
Often its useful to delay the screenshot if you want to bring up some tool tip or popup to be displayed in the screenshot.

Currently it does not look like this is possible and would be a nice feature to have, an OSD counting down would also be a nice feature :)

**Comment by OttoAllmendinger** [comment]
Thanks for your suggestion. Please upvote issue #2 :)

**Comment by olymk2** [comment]
Done and thanks for the very helpful plugin :)
