### ISSUE TITLE
Preferences do not work

### ISSUE THREAD

**Issue by thankjura** [OttoAllmendinger/gnome-shell-screenshot#45]
Error: Expected type utf8 for Argument 'key' but got type 'undefined'

Stack trace:
  buildConfigSwitch@/home/GrandMaster/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/prefs.js:51:22
  ScreenshotToolSettingsWidget<._makePrefsIndicator@/home/GrandMaster/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/prefs.js:117:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  ScreenshotToolSettingsWidget<._initLayout@/home/GrandMaster/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/prefs.js:86:12
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  ScreenshotToolSettingsWidget<._init@/home/GrandMaster/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/prefs.js:78:5
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/GrandMaster/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/prefs.js:538:16
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._extensionFound/<@resource:///org/gnome/shell/extensionPrefs/main.js:209:17
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43

gnome-3.25.92

**Comment by OttoAllmendinger** [comment]
is this with the extensions.gnome.org version or the master branch version?

**Comment by thankjura** [comment]
master branch version

**Comment by OttoAllmendinger** [comment]
Looks like there is a breaking change coming in gnome-3.25, will see if I can track it down. Thanks for the head's up.

**Comment by thankjura** [comment]
#46

**Comment by OttoAllmendinger** [comment]
See #46
