### ISSUE TITLE
Option to automatically copy to clipboard?

### ISSUE THREAD

**Issue by orschiro** [OttoAllmendinger/gnome-shell-screenshot#48]
Dear @OttoAllmendinger,

Would you consider an option in the settings to always automatically copy the image to clipboard?

**Comment by OttoAllmendinger** [comment]
It already exists, the setting is called "Default Clipboard Content"

**Comment by orschiro** [comment]
Got you!

Thanks. :-)

Wasn't obvious to me. Maybe call it "Automatically copy to clipboard"?

**Comment by OttoAllmendinger** [comment]
The problem there is that the auto-copy url function for imgur will override this (as it currently does). The dropdown should contain the options "default", "image data" and "imgur URL". It is actually a bug that it is not like that at the moment.

But I agree the naming is suboptimal ;)

**Comment by orschiro** [comment]
Haha, I see. 

Maybe say:

Default Clipboard Content: Image data

And then below a sentence that says:

"Select Image Data to automatically copy screenshots to clipboard"

**Comment by orschiro** [comment]
Hence no changes to the text for now?

**Comment by OttoAllmendinger** [comment]
Not for now, and the confusing text is a separate issue. 

Your suggestion goes in the right direction but is a bit to verbose. 

Maybe it should say not "Default Clipboard Content" but instead 

`Auto-copy to clipboard: "Nothing"/"Image Data"/"Imgur Link"`

**Comment by orschiro** [comment]
> Auto-copy to clipboard: "Nothing"/"Image Data"/"Imgur Link"

Nice, like this one! 

Can we implement that?

**Comment by OttoAllmendinger** [comment]
Yes, https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/50

Downside is that translations need to updated

**Comment by OttoAllmendinger** [comment]
Cool!

Yes, it is that folder but I will have to update somefiles before you can change them. I will do it later today :)

**Comment by orschiro** [comment]
Nice! Let me know when I can start. :-)
