### ISSUE TITLE
Check unicode errors when writing files

### ISSUE THREAD

**Issue by OttoAllmendinger** [OttoAllmendinger/gnome-shell-screenshot#49]
Google translate from russian e.o.g comment:

> In the Russian version, it tries to save a snapshot to the "Images" folder ... but writes "rubbish with squares" on the way. Vanguuy mistake in with encoding. I ask to correct

**Comment by thankjura** [comment]
![image](https://user-images.githubusercontent.com/2144212/35054891-cbcf6f10-fbbe-11e7-846e-13ae257e713f.png)
On save screenshot

**Comment by OttoAllmendinger** [comment]
fixed in https://github.com/OttoAllmendinger/gnome-shell-screenshot/commit/3ebcc2ea4860eab70c70ff08ea03625849d83cea
