### ISSUE TITLE
.scaled images are saved

### ISSUE THREAD

**Issue by phocean** [OttoAllmendinger/gnome-shell-screenshot#5]
Hello,

Thank you, it is a very nice extension :-)

But the .scaled image used for notifications should not be saved besides the screenshot itself.
Is it only necessary?

**Comment by jwarkentin** [comment]
I'm not sure what the point of auto-saving the scaled image is but if there is a purpose to it then it would be nice to at least have an option to disable saving of scaled images. I hate getting two images every time I take a screenshot.

**Comment by OttoAllmendinger** [comment]
Yes, there scaled image should not be saved in the same location where the actual screenshot is. It should be an easy fix.

**Comment by jwarkentin** [comment]
I just updated the extension but I'm still getting the extra scaled image saved in the directory I set for autosave.

**Comment by OttoAllmendinger** [comment]
Did you update from extensions.gnome.org or did you `make install` the current master branch?

**Comment by phocean** [comment]
Yes, it is fixed, thank you!

**Comment by jwarkentin** [comment]
Oh, I updated from extensions.gnome.org. I'm guessing the updated version is not on there yet then. I'll update when it's available. Thanks!
