### ISSUE TITLE
Ability to define manual folder to save screenshot

### ISSUE THREAD

**Issue by orschiro** [OttoAllmendinger/gnome-shell-screenshot#53]
Hi all, 

Enabled auto-save to the folder Pictures, yet wish to manually save to a custom folder occasionally.

This doesn't seem to work [1].

Any solutions?

Thank you!

[1] https://www.useloom.com/share/9d92ca1f60dd4791bccea84a30c164f1

**Comment by OttoAllmendinger** [comment]
That is indeed a bug, the reason is that the suggested filename (at the top) is the full path. It should be just the basename.

**Comment by orschiro** [comment]
Wow that was fast! :-)

Thank you
