### ISSUE TITLE
Optional setting to disable the notification?

### ISSUE THREAD

**Issue by orschiro** [OttoAllmendinger/gnome-shell-screenshot#54]
I have set Gnome Shell Screenshot to auto-save and auto-copy to clipboard. 

Hence I don't need this notification shown below. 

What do you think of an optional setting to disable notifications? :-)

![image](https://user-images.githubusercontent.com/170947/32163921-30545dbe-bd5e-11e7-9271-f01e19c14eab.png)

**Comment by OttoAllmendinger** [comment]
good idea!

**Comment by orschiro** [comment]
Cool, thanks! Let me know when I can test or provide any kind of other
input. ☺

**Comment by orschiro** [comment]
@OttoAllmendinger any news on this? Is this a complex feature? I don't have a lot of coding experience but can I maybe help somehow?

**Comment by OttoAllmendinger** [comment]
merged in master :)

**Comment by orschiro** [comment]
Woow, that was fast :-D

Going to check tomorrow if it's already available on Gnome extensions. Thanks so much!

**Comment by OttoAllmendinger** [comment]
thanks! it can take between a few days and a few weeks until it is approved tough

**Comment by orschiro** [comment]
OK, will let everyone know here once I received the update. :-)

**Comment by orschiro** [comment]
Still not updated I think. :-P

Well one day it will be. :-D
