### ISSUE TITLE
Blue overlay is not removed on a second screen

### ISSUE THREAD

**Issue by malexandre** [OttoAllmendinger/gnome-shell-screenshot#56]
Hi!

I'm on Gnome Shell 3.26.1 & Gnome Screenshot 3.26.0. extensions.gnome.org tells me the Screenshot Tool is up to date, so it should be the v21.

When I selecting a zone on my main screen, everything works fine. But on my second screen (connected by USB-C, 1440p vs 1080p for my main screen, maybe it's important), the blue overlay is not removed from the screenshot.

Main screen:
![Main screen](https://i.imgur.com/C5Blhzf.png)

Second screen:
![Second screen](https://i.imgur.com/DcTHFEx.png)

**Comment by OttoAllmendinger** [comment]
Thanks, this is a known issue (See #28)

The fix I have in mind is to introduce the delay option (#2) and allow a very short delay (10ms).

**Comment by malexandre** [comment]
Sorry, didn't see the first issue. Thank you for your quick answer, I'll follow the other issues then.
