### ISSUE TITLE
Allow users to upload to custom servers

### ISSUE THREAD

**Issue by lamehost** [OttoAllmendinger/gnome-shell-screenshot#58]
Hello,

I love your extension, it's well done and works smoothly, but for security reason i can't upload my screenshots on imgur.

So i hacked your code on my laptop and changed these two lines in [uploadImgur.js](https://github.com/OttoAllmendinger/gnome-shell-screenshot/blob/master/src/uploadImgur.js) to point your client to my own REST interface.
```
const clientId = "c5c1369fb46f29e";
const baseUrl = "https://api.imgur.com/3/";
```

Everything works good, but i wonder if you could allow users to do that via GUI.
In case that you're wondering what servers users could upload to: [i wrote my own](https://github.com/lamehost/anastasia/tree/master).

Thanks

**Comment by OttoAllmendinger** [comment]
Interesting idea, but would be a bit of a pain to test. 

I will probably add support for shell command hooks first (#15), which covers a lot of your use case as well.

**Comment by AskAlice** [comment]
+1 this idea please for both of these concepts.

**Comment by gabrielklein** [comment]
I would love the option to upload to nextcloud, and dropbox :)

**Comment by sebastienserre** [comment]
To upload to Nextcloud, maybe it can added to Dropit: https://github.com/rullzer/dropit

**Comment by OttoAllmendinger** [comment]
As a workaround, you can now run custom commands: https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/15#issuecomment-748811544

**Comment by lamehost** [comment]
Looks like a reasonable alternative, thanks!
