### ISSUE TITLE
Allow different click actions for different mouse buttons

### ISSUE THREAD

**Issue by gsantner** [OttoAllmendinger/gnome-shell-screenshot#6]
Please allow the current notification click actions to be defined differently for other mouse keys.
e.g. So this could be possible:

- Left click: Area
- Right click: Menu
- Middle click: Window

**Comment by OttoAllmendinger** [comment]
Interesting idea. 

I'm a bit hesitant because gnome-shell usually is not left-click / right-click sensitive (touchscreen-ready and all that). But as an explicit power-user setting it should be ok.

**Comment by OttoAllmendinger** [comment]
I changed it so that you can only override the primary button action. The secondary button now always shows the menu. 

I think I'll keep it that way for now since I would like to add more functionality to the menu.
