### ISSUE TITLE
Add a time to take a screenshot

### ISSUE THREAD

**Issue by xkill** [OttoAllmendinger/gnome-shell-screenshot#63]
I suggest to add a timer to take the screenshots, so if you have to take a screenshot after performing any action with the keyboard or mouse, you will have enough time to do it before getting the screenshot.

**Comment by OttoAllmendinger** [comment]
duplicate of #2 

coming soon ;)

**Comment by brunofin** [comment]
It's not like I have a lot of spare time, but I am interested in learning, do you need some help for this issue maybe?
