### ISSUE TITLE
Permissions when saving files

### ISSUE THREAD

**Issue by isaaclw** [OttoAllmendinger/gnome-shell-screenshot#64]
I take screenshots, and want to share them with co-workers on my own http/nginx deployment.

But the screenshots are all saved with 0600 permissions, which means unless I change my http user to be my current user, or I manually (or automatically) run chmod on all those files, there's no way for my nginx application to read the screenshots I save.

I can't find in the code where it does this.

$ lsb_release -da
Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch

**Comment by OttoAllmendinger** [comment]
Does https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/15#issuecomment-748811544 fix it for you?

**Comment by isaaclw** [comment]
Yes! Thank you.
