### ISSUE TITLE
Error:exitCode=256

### ISSUE THREAD

**Issue by Criptos** [OttoAllmendinger/gnome-shell-screenshot#74]
When selecting an area, I got this error... 

Any advise? 

Fedora 27.

**Comment by Criptos** [comment]
An upadate fixed my issue... thanks! 
 
You should also have a paypal account... sometimes btc tips tend to be more expensive and compex than paypal...

**Comment by Criptos** [comment]
No, againt  I got the error... how to debug it ? 
I'm using fedora 27 
I update from fedora 26 and it was working flawlessly...

**Comment by OttoAllmendinger** [comment]
1. Can you give me the output of `cat  ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json`
2. Are you using display scaling?
3. Does it work if you take a small screenshot in (1) the upper-left corner of the screen? (2) The bottom-right corner?

**Comment by OttoAllmendinger** [comment]
Thanks for the response. This is a known issue that is fixed in the latest version. You can either install from git or wait until the new version is approved on https://extensions.gnome.org/extension/1112/screenshot-tool/.
