### ISSUE TITLE
I have a personal place to send images.

### ISSUE THREAD

**Issue by wherkamp** [OttoAllmendinger/gnome-shell-screenshot#76]
How would I configure gnome-shell-screenshot to post request it to this.

**Comment by OttoAllmendinger** [comment]
Would https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/15 work for you?

**Comment by wherkamp** [comment]
Yea, I can't wait till that gets implemented.

**Comment by OttoAllmendinger** [comment]
Only a matter of time ;)

**Comment by wherkamp** [comment]
YAY!
