### ISSUE TITLE
Crashes Gnome?

### ISSUE THREAD

**Issue by Paralusion** [OttoAllmendinger/gnome-shell-screenshot#78]
Sometimes when I try to take a screenshot, the shell gets restarted. Is there a way to fix this?

**Comment by a1ad** [comment]
Same here, after i updated the extension i now have a [error](https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/80) code

**Comment by OttoAllmendinger** [comment]
@a1ad does the shell restart or crash gnome when the error happens?

**Comment by a1ad** [comment]
It wasn't crashing anymore, just the (permission) error, see [update](https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/80)
