### ISSUE TITLE
error: exitCode=256

### ISSUE THREAD

**Issue by a1ad** [OttoAllmendinger/gnome-shell-screenshot#80]
when taking a screenshot i get the following error code: [Error](https://www.dropbox.com/s/p96wszuyc4c5vwe/error.png?dl=0)

cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Conveniently create, copy, store and upload screenshots", 
  "gettext-domain": "gnome-shell-screenshot", 
  "name": "Screenshot Tool", 
  "settings-schema": "org.gnome.shell.extensions.screenshot", 
  "shell-version": [
    "3.24", 
    "3.26", 
    "3.28"
  ], 
  "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/", 
  "uuid": "gnome-shell-screenshot@ttll.de", 
  "version": 30

gnome-shell --version
GNOME Shell 3.28.3

**Comment by OttoAllmendinger** [comment]
@a1ad please run this command and paste the output
```
gjs ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/auxhelper.js --desktop --filename /tmp/test.png --debug
```

**Comment by a1ad** [comment]
@OttoAllmendinger thanks you put me in the right direction, it is a firejail permission issue
