### ISSUE TITLE
Screenshot tool not working on Ubuntu 18.10

### ISSUE THREAD

**Issue by CrazyLemon** [OttoAllmendinger/gnome-shell-screenshot#82]
So the icon is there but the issue is that it semi-hangs the system when you want to use it in any way.
The error that is shown is "global.screen is undefined" and than you can interact with the system just enough that you can reboot it.

So global.screen function doesn't exists anymore and IMO you should be using something like https://github.com/micheleg/dash-to-dock/pull/770

**Comment by OttoAllmendinger** [comment]
This is fixed in the most recent version in this repo, and on extensions.gnome.org. Please make sure you have latest version installed.

If the problem persists, please tell me the gnome-shell version you are using.

**Comment by CrazyLemon** [comment]
Ok .. that is strange. I already removed and readded the extension and it was the same behavior.
Now i've installed it again and is working as it should.

Sorry for the noise :)
