### ISSUE TITLE
User-customizeable filename

### ISSUE THREAD

**Issue by yafp** [OttoAllmendinger/gnome-shell-screenshot#9]
It would be a great feature if users could define a naming pattern for the screenshots in the extension settings.

Personally i dislike blanks in filenames, timezone isn't important for me and the day/month isn't needed either - all those facts could be solved with a user-defined naming.

It would need some predefined keywords like
- Date
- Time
- Hostname
- Dimensions

some of those with parameters like
- Date(Ymd)

in combination with plain strings

Example:
`MyUeberScreenshotName_%Date(Ymd)%_%Dimension%_%Hostname%`

Results in:
`MyUeberScreenshotName_20161123_800x600_pcname.png`

**Comment by OttoAllmendinger** [comment]
Please test the master branch. The available parameters are displayed as the entry tooltip.

**Comment by yafp** [comment]
Looks great - thank you very much. Feel free to close the issue/request

PS: Adding hostname as parameter would make it perfect ;)

**Comment by OttoAllmendinger** [comment]
Done

I'm running out of letters in the alphabet ;) 


Implementing #15 would be a general solution I hope.

**Comment by yafp** [comment]
you are awesome
