### ISSUE TITLE
Version from extensions.gnome.org does not work on Gnome 3.32.2

### ISSUE THREAD

**Issue by leoheck** [OttoAllmendinger/gnome-shell-screenshot#97]
I don't know the required info you need to fix it. But please, let me know and I will get it.
I am living without the most important extension for 5 days. I use this tool about every hour, seriously. We need to fix it. Just let me know anything you need guys!

![image](https://user-images.githubusercontent.com/1277920/65391495-4eba7a00-dd40-11e9-8ba7-fab930b2b3c3.png)

EDIT: Add a workaround.
EDIT2: Add a new command to activate the changes.

So, the workaround is to install it manually, after that the updates are working too.
```
# Download the sources
git clone https://github.com/OttoAllmendinger/gnome-shell-screenshot.git
cd gnome-shell-screenshot

# Install it
make install

# Log out then log in again to activate the changes OR execute the following command
# PLEASE save your files to avoid any issue.
make restart
```

**Comment by leoheck** [comment]
Oh, I am using Ubuntu 19.04

**Comment by leoheck** [comment]
@OttoAllmendinger 
```
➜ cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json

{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Conveniently create, copy, store and upload screenshots", 
  "gettext-domain": "gnome-shell-screenshot", 
  "name": "Screenshot Tool", 
  "settings-schema": "org.gnome.shell.extensions.screenshot", 
  "shell-version": [
    "3.28", 
    "3.30", 
    "3.34", 
    "3.32"
  ], 
  "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/", 
  "uuid": "gnome-shell-screenshot@ttll.de", 
  "version": 37
}%                                                                                                                                            
```

**Comment by valteau** [comment]
Hello, I have the same with the same config.

Ubuntu 19.04

 cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json

{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Conveniently create, copy, store and upload screenshots", 
  "gettext-domain": "gnome-shell-screenshot", 
  "name": "Screenshot Tool", 
  "settings-schema": "org.gnome.shell.extensions.screenshot", 
  "shell-version": [
    "3.28", 
    "3.30", 
    "3.34", 
    "3.32"
  ], 
  "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/", 
  "uuid": "gnome-shell-screenshot@ttll.de", 
  "version": 37
}

The error msg from lg is "TypeError: getActorCompat( ?. ).add is not a function.

And a big thanks for this usefull extensions !!

**Comment by stefangweichinger** [comment]
I also face issues, Fedora30 here. pls advise what to post here (where to look for errors). thx

**Comment by OttoAllmendinger** [comment]
@stefangweichinger please provide the outputs of 

```
cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
```

and 

```
journalctl -b /usr/bin/gnome-shell
```

**Comment by stefangweichinger** [comment]
```
~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Conveniently create, copy, store and upload screenshots", 
  "gettext-domain": "gnome-shell-screenshot", 
  "name": "Screenshot Tool", 
  "settings-schema": "org.gnome.shell.extensions.screenshot", 
  "shell-version": [
    "3.28", 
    "3.30", 
    "3.34", 
    "3.32"
  ], 
  "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/", 
  "uuid": "gnome-shell-screenshot@ttll.de", 
  "version": 37
```
That journalctl-output is huge, I will reboot asap and post then.

**Comment by stefangweichinger** [comment]
```
# tail ... when trying to install your extension

Sep 23 14:12:52 x1 gnome-shell[4435]: [pixel-saver]: Could not find XID for window with title Terminal
Sep 23 14:12:52 x1 gnome-shell[4435]: [pixel-saver]: Could not find XID for window with title Terminal
Sep 23 14:12:52 x1 gnome-shell[4435]: [pixel-saver]: Could not find XID for window with title Terminal
Sep 23 14:12:52 x1 gnome-shell[4435]: [pixel-saver]: Finding XID for window Terminal failed
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]: Archive:  /tmp/IMUS8Z.shell-extension.zip
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/cs/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/indicator.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/auxhelper.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/stylesheet.css
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/schemas/gschemas.compiled
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/de/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/uploadDummy.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/zh_CN/LC_MESSAGES/gnome-s>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/notifications.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/el/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/selection.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/config.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/pt_BR/LC_MESSAGES/gnome-s>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/tr/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/dump.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/ru/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/empty64.png
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/thumbnail.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/path.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/version.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/fr/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/schemas/org.gnome.shell.extensio>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/clipboard.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/uploadImgur.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/filename.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/convenience.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/uk/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/vendor/stringformat.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/prefs.js
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/pl/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:   inflating: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/locale/it/LC_MESSAGES/gnome-shel>
Sep 23 14:13:13 x1 org.gnome.Shell.desktop[4435]:  extracting: /home/sgw/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
Sep 23 14:13:13 x1 gnome-shell[4435]: Extension "gnome-shell-screenshot@ttll.de" had error: TypeError: getActorCompat(...).add is not a function

```

**Comment by leoheck** [comment]
@OttoAllmendinger I was trying to install it on a second computer, it is the same. Same issue.
I was able to install it manually. But not through the website.

**Comment by leoheck** [comment]
```bash
gnome-shell-screenshot on  master [!] 
➜ cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json

{
    "shell-version": ["3.28", "3.30", "3.32", "3.34"],
    "uuid": "gnome-shell-screenshot@ttll.de",
    "name": "Screenshot Tool",
    "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/",
    "description": "Conveniently create, copy, store and upload screenshots",
    "settings-schema":  "org.gnome.shell.extensions.screenshot",
    "gettext-domain": "gnome-shell-screenshot"
}
```

**Comment by OttoAllmendinger** [comment]
@stefangweichinger thanks, can you please also give me the output of `gnome-shell --version`?

@leoheck is the git master version crashing on the second computer? can you give me the output of `gnome-shell --version` there and the output `journalctl -b /usr/bin/gnome-shell` (just the stack trace is enough)?

**Comment by stefangweichinger** [comment]
```
$ gnome-shell --version
GNOME Shell 3.32.2
```

**Comment by leoheck** [comment]
The GitHub/master is working just fine (I've put a workaround on the top of this thread)
```
➜ gnome-shell --version 
GNOME Shell 3.32.2
```
The issue is to upgrade it from the website.
But after installing the GitHub/master the update works fine again.

**Comment by leoheck** [comment]
The log is here

--
Leandro Heck

**Comment by stefangweichinger** [comment]
> The GitHub/master is working just fine (I've put a workaround on the top of this thread)

workaround works for me; thanks!

**Comment by OttoAllmendinger** [comment]
@stefangweichinger @leoheck if you now install the version from extensions.gnome.org again, does it still work?

**Comment by stefangweichinger** [comment]
> @stefangweichinger @leoheck if you now install the version from extensions.gnome.org again, does it still work?

I removed it via the "red X" button and re-installed via "ON" ... yes, that works now.

**Comment by pedrospdc** [comment]
Same error.
Ubuntu 19.04
`veye → git feat/e2e-helpers* → cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Conveniently create, copy, store and upload screenshots", 
  "gettext-domain": "gnome-shell-screenshot", 
  "name": "Screenshot Tool", 
  "settings-schema": "org.gnome.shell.extensions.screenshot", 
  "shell-version": [
    "3.28", 
    "3.30", 
    "3.34", 
    "3.32"
  ], 
  "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/", 
  "uuid": "gnome-shell-screenshot@ttll.de", 
  "version": 37
}%     `

**Comment by OttoAllmendinger** [comment]
@pedrospdc does removing the extension and re-installing it from the store change anything?

**Comment by binnih** [comment]
Removing and installing from gnome extensions page changes nothing, still not working. 
Using Fedora 30 - NOME Shell 3.32.2.

Workaround here at the top is not working for me.

**Comment by binnih** [comment]
Sep 23 15:38:02 lagbh gnome-shell[3025]: Extension "gnome-shell-screenshot@ttll.de" had error: TypeError: getActorCompat(...).add is not a function

**Comment by OttoAllmendinger** [comment]
@binnih please give the output of `cat ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/metadata.json`

**Comment by binnih** [comment]
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Conveniently create, copy, store and upload screenshots", 
  "gettext-domain": "gnome-shell-screenshot", 
  "name": "Screenshot Tool", 
  "settings-schema": "org.gnome.shell.extensions.screenshot", 
  "shell-version": [
    "3.28", 
    "3.30", 
    "3.34", 
    "3.32"
  ], 
  "url": "https://github.com/OttoAllmendinger/gnome-shell-screenshot/", 
  "uuid": "gnome-shell-screenshot@ttll.de", 
  "version": 37

**Comment by OttoAllmendinger** [comment]
@binnih it looks like your local installation failed via `git clone` failed

please try this: https://github.com/OttoAllmendinger/gnome-shell-screenshot#via-githubcom

**Comment by binnih** [comment]
After following this
--
git clone https://github.com/OttoAllmendinger/gnome-shell-screenshot.git
cd gnome-shell-screenshot
make install
--

Gnome tweaks does not show Screenshot tool installed and the gnome extensions just shows it uninstalled.

**Comment by OttoAllmendinger** [comment]
@binnih please log out and log back in again

**Comment by leoheck** [comment]
@binnih sorry, I forget to tell to log out and log back in again to activate the settings as @OttoAllmendinger said. (I just updated the instructions in the 1st message of this thread)

**Comment by Burday** [comment]
I'm having the same issue from extensions.gnome.org . Tried reinstalling the tool, updating the system and restarting the PC, but nothing works at the moment. I still have an error on extensions.gnome.org.  Any ideas as to why is that, what I can do to fix it and when will an official fix come out?

**Comment by OttoAllmendinger** [comment]
@Burday I'm trying to figure out why the installation from e.g.o doesn't work. It should be identical to the `master` branch.

However, for most people installing from the repo seems to fix the issue. See instructions here: https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/97#issue-496804355

**Comment by OttoAllmendinger** [comment]
@Burday before you try the workaround, can you please submit a copy of your extension?

```
cd ~/.local/share/gnome-shell/extensions
zip -r ~/gsescr.zip gnome-shell-screenshot@ttll.de/
```

**Comment by Burday** [comment]
[here](https://www.dropbox.com/s/esfiz8e2if91yps/gsescr.zip?dl=0)

**Comment by OttoAllmendinger** [comment]
@Burday thanks. It looks like a normal installation, so I can exclude the possibility that the wrong code gets installed. Please try the workaround I mentioned and see if it works.

**Comment by OttoAllmendinger** [comment]
I have reproduced the error on Gnome 3.32.2 when upgrading to v37.

However, logging out and logging in again seems to fix it on the system I'm testing on.

**Comment by Burday** [comment]
I tried installing via GitHub with the method provided on the page, but I don't see the extension on https://extensions.gnome.org/local/ . Any ideas?

**Comment by binnih** [comment]
I installed from gnome extensions website, got an error and then rebooted. After reboot it works fine.
Thank you!

**Comment by OttoAllmendinger** [comment]
@Burday please try this

1.
```
rm -rf ~/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/
```

2. reinstall from https://extensions.gnome.org/extension/1112/screenshot-tool/
3. log out and log in again

**Comment by Burday** [comment]
After a reinstall, system update and restart, the issue is fixed for my machine.

**Comment by Burday** [comment]
I think this issue can be closed now

**Comment by OttoAllmendinger** [comment]
thanks everybody for helping test this
