### ISSUE TITLE
feature request >> basic editing tool ?

### ISSUE THREAD

**Issue by dgoosens** [OttoAllmendinger/gnome-shell-screenshot#99]
hi,

Wondering if there are plans or if it would be feasible to implement a basic editing tool ?

- resize
- drop down shadows
- show something with an arrow
- highlight text
- put a rectangle around something

Any plans for something like that ?
dGO

**Comment by OttoAllmendinger** [comment]
duplicate of https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/35
